"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";
import { NAV_ITEMS, type NavItem } from "@/constants/nav";
import { useAuth } from "@/providers/auth-provider";
import { ChevronLeft, ChevronRight, Menu, Store, X } from "lucide-react";

export function Sidebar() {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false);
  const pathname = usePathname(); const { user } = useAuth();
  const visibleItems = NAV_ITEMS.filter((item) => !!user && item.roles.includes(user.role));
  return <><button onClick={() => setMobileOpen(true)} className="fixed bottom-5 left-5 z-40 rounded-full bg-blue-600 p-3 text-white shadow-lg md:hidden" aria-label="Open navigation"><Menu className="h-5 w-5" /></button>{mobileOpen && <button onClick={() => setMobileOpen(false)} className="fixed inset-0 z-40 bg-slate-950/30 md:hidden" aria-label="Close navigation overlay" />}<aside className={cn("fixed inset-y-0 left-0 z-50 flex h-screen -translate-x-full flex-col border-r border-gray-200 bg-white transition-all duration-300 md:static md:translate-x-0", mobileOpen && "translate-x-0", collapsed ? "w-16" : "w-64")}><div className="flex h-16 items-center justify-between border-b border-gray-200 px-4"><button onClick={() => setMobileOpen(false)} className="rounded p-1 text-gray-500 md:hidden" aria-label="Close menu"><X className="h-5 w-5" /></button>{!collapsed && <div className="flex items-center gap-2"><Store className="h-6 w-6 text-blue-600" /><span className="text-lg font-bold text-gray-900">CommercePilot</span></div>}{collapsed && <Store className="mx-auto h-6 w-6 text-blue-600" />}<button onClick={() => setCollapsed(!collapsed)} className="hidden rounded p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600 md:block">{collapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button></div><nav className="flex-1 space-y-1 px-2 py-4">{visibleItems.map((item: NavItem) => { const active = item.href === "/dashboard" ? pathname === "/dashboard" : pathname.startsWith(item.href); const Icon = item.icon; return <Link key={item.href} href={item.href} onClick={() => setMobileOpen(false)} className={cn("flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors", active ? "bg-blue-50 text-blue-700" : "text-gray-600 hover:bg-gray-50 hover:text-gray-900", collapsed && "justify-center px-2")} title={collapsed ? item.label : undefined}><Icon className="h-5 w-5 shrink-0" />{!collapsed && <span>{item.label}</span>}</Link>; })}</nav>{!collapsed && user && <div className="border-t border-gray-200 p-4"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-sm font-medium text-blue-700">{user.name.charAt(0).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-medium text-gray-900">{user.name}</p><p className="text-xs text-gray-500">{user.role === "owner" ? "Store Owner" : user.role}</p></div></div></div>}</aside></>;
}
