"use client";

import { use, useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, Star } from "lucide-react";
import { MarketingShell } from "@/components/marketing/MarketingShell";
import { usePublicProduct, usePublicProducts } from "@/features/products/hooks/usePublicProducts";
import { formatCurrency, formatDate } from "@/lib/utils";

type Review = { name: string; rating: number; text: string; date: string };
const fallback = "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80";

export default function PublicItemDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const { data: product, isLoading, error } = usePublicProduct(id); const { data: related } = usePublicProducts({ limit: 4, sortBy: "createdAt", order: "desc" });
  const [rating, setRating] = useState(5); const [text, setText] = useState(""); const [reviews, setReviews] = useState<Review[]>(() => { if (typeof window === "undefined") return []; try { return JSON.parse(window.localStorage.getItem(`reviews:${id}`) || "[]") as Review[]; } catch { return []; } });
  const submitReview = (event: React.FormEvent) => { event.preventDefault(); if (!text.trim()) return; const next = [{ name: "Verified visitor", rating, text: text.trim(), date: new Date().toISOString() }, ...reviews]; setReviews(next); window.localStorage.setItem(`reviews:${id}`, JSON.stringify(next)); setText(""); };
  const relatedItems = useMemo(() => (related?.items || []).filter((item) => item._id !== id).slice(0, 3), [related?.items, id]);
  if (isLoading) return <MarketingShell><div className="mx-auto max-w-7xl px-4 py-16"><div className="h-96 animate-pulse rounded-xl bg-slate-200" /></div></MarketingShell>;
  if (error || !product) return <MarketingShell><div className="mx-auto max-w-3xl px-4 py-16 text-center"><h1 className="text-2xl font-bold">Product not found</h1><Link href="/items" className="mt-5 inline-block text-blue-600">Return to catalog</Link></div></MarketingShell>;
  return <MarketingShell><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><Link href="/items" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-blue-700"><ArrowLeft className="h-4 w-4" /> Back to catalog</Link><section className="mt-6 grid gap-8 lg:grid-cols-2"><div className="grid gap-3 sm:grid-cols-2"><Image src={product.images[0] || fallback} alt={product.name} width={800} height={380} className="h-[380px] w-full rounded-xl object-cover sm:col-span-2" unoptimized />{product.images.slice(1, 3).map((image) => <Image key={image} src={image} alt={`${product.name} product view`} width={400} height={160} className="h-40 w-full rounded-xl object-cover" unoptimized />)}</div><div><p className="text-sm font-bold uppercase tracking-wider text-blue-600">Product overview</p><h1 className="mt-2 text-4xl font-bold">{product.name}</h1><p className="mt-4 text-lg leading-8 text-slate-600">{product.description || "Explore this live CommercePilot catalog item for current product information."}</p><p className="mt-6 text-3xl font-bold">{formatCurrency(product.discountPrice || product.sellingPrice)}</p>{product.discountPrice && product.discountPrice < product.sellingPrice && <p className="mt-1 text-sm text-slate-500 line-through">{formatCurrency(product.sellingPrice)}</p>}{product.tags.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{product.tags.map((tag) => <span key={tag} className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{tag}</span>)}</div>}</div></section>
  <section className="mt-10 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Specifications</h2><dl className="mt-5 grid gap-x-8 gap-y-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">SKU</dt><dd className="mt-1 font-mono font-semibold">{product.sku}</dd></div>{product.barcode && <div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">Barcode</dt><dd className="mt-1 font-mono font-semibold">{product.barcode}</dd></div>}<div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">Availability</dt><dd className="mt-1 font-semibold">{product.stock > 0 ? `${product.stock} in stock` : "Out of stock"}</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">Priority</dt><dd className="mt-1 font-semibold capitalize">{product.priority || "Standard"}</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">Available from</dt><dd className="mt-1 font-semibold">{product.availableFrom ? formatDate(product.availableFrom) : "Immediately"}</dd></div><div className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">Listed</dt><dd className="mt-1 font-semibold">{formatDate(product.createdAt)}</dd></div></dl></section>
  <section className="mt-14 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><h2 className="text-2xl font-bold">Ratings & reviews</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><Star className="h-4 w-4 fill-amber-400 text-amber-400" /> 4.8 average customer rating</p><form onSubmit={submitReview} className="mt-6 rounded-xl border border-slate-200 bg-white p-5"><div className="flex gap-1">{[1,2,3,4,5].map((value) => <button type="button" key={value} onClick={() => setRating(value)} aria-label={`${value} stars`}><Star className={`h-5 w-5 ${value <= rating ? "fill-amber-400 text-amber-400" : "text-slate-300"}`} /></button>)}</div><textarea value={text} onChange={(e) => setText(e.target.value)} required rows={3} placeholder="Share a helpful review" className="mt-3 w-full rounded-lg border border-slate-300 p-3 text-sm" /><button className="mt-3 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Post review</button></form><div className="mt-5 space-y-3">{reviews.map((review, index) => <article key={`${review.date}-${index}`} className="rounded-xl border border-slate-200 bg-white p-5"><p className="font-semibold">{review.name}</p><p className="mt-1 flex items-center gap-1 text-sm text-amber-500"><Star className="h-4 w-4 fill-amber-400" /> {review.rating}/5</p><p className="mt-2 text-sm text-slate-600">{review.text}</p></article>)}</div></div><aside className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">Quick info</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-slate-500">Product ID</dt><dd className="mt-1 break-all font-mono text-xs">{product._id}</dd></div>{product.barcode && <div><dt className="text-slate-500">Barcode</dt><dd className="mt-1 font-mono text-xs font-semibold">{product.barcode}</dd></div>}<div><dt className="text-slate-500">Last updated</dt><dd className="mt-1 font-semibold">{formatDate(product.updatedAt)}</dd></div></dl></aside></section>
  <section className="mt-14"><h2 className="text-2xl font-bold">Similar products</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{relatedItems.map((item) => <Link href={`/items/${item._id}`} key={item._id} className="overflow-hidden rounded-xl border border-slate-200 bg-white hover:shadow-md"><Image src={item.images[0] || fallback} alt="" width={400} height={144} className="h-36 w-full object-cover" unoptimized /><div className="p-4"><p className="font-bold">{item.name}</p><p className="mt-1 text-sm text-slate-600">{formatCurrency(item.discountPrice || item.sellingPrice)}</p></div></Link>)}</div></section></main></MarketingShell>;
}

